version: "3"
services:
  scans:
    # command: python -v
    build: .
    image: "tc-hosts-scans"
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials
    environment:
      - DEBUG_SENT_EMAIL=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
